service: lambda-file-converter
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  ecr:
    images:
      node16-libre-lambda:
        path: ./
  environment:
    CONVERTED_FILE_UPLOAD_BUCKET: !Ref StoreConvertedFiles

functions:
  convertFile:
    image:
      name: node16-libre-lambda
    events:
      - s3:
          bucket: !Ref ConvertFileUploads
          event: s3:ObjectCreated:*
          existing: true

resources:
  Resources:
    ConvertFileUploads:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: convert-file-uploads
    StoreConvertedFiles:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: store-converted-files
